### ISSUE TITLE
Question: TimeZones

### ISSUE THREAD

**Issue by halal-beef** [PrayerTimeResearch/PrayerTimeAPI#26]
How do you use timezones, i see you use Europe/London but how would we integrate other timezones like American timezones?

**Comment by nnym** [comment]
Check out https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. I've found that the time zone only adjusts the returned times so you could also always use UTC and add the local time zone's offset manually. Also, [ISO 8601 time zone designators](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) won't work because they seem to not give the right adjustments as if UTC+0 is used.

**Comment by halal-beef** [comment]
Thank you
